---
title: "class12"
output: github_document
---


# Setup HIV-pr for docking study

Retrieving pdb file on protein
```{r}

library(bio3d)
file.name <- get.pdb("1hsg")

```

Read file in and trim out protein, small molecule ligand

```{r}
hiv <- read.pdb(file.name)
hiv
```

```{r}
ligand <- trim.pdb(hiv, "ligand")
ligand
```

Extract protein

```{r}
protein <- trim.pdb(hiv, "protein")
protein
```

<<<<<<< HEAD
```{r}
write.pdb(ligand, "1hsg_ligand.pdb")
write.pdb(protein, "1hsg_protein.pdb")
```
=======
## Processing docking results

```{r}
library(bio3d) 
res <- read.pdb("all.pdbqt", multi=TRUE)
write.pdb(res, "results.pdb")

```

Compare our results to Merck's drug crystal structure 
>>>>>>> d5dd8f16eb1a6e05bdc5710783b80f4619e1f395

```{r}
ori <- read.pdb("1hsg_ligand.pdbqt")
```

Calculating Root Mean Square Distance (RMSD)

```{r}
rmsd(ori, res)
```

**Q6** RMSD based on non hydrogen atoms

```{r}
inds <- atom.select(ori, "noh")

rmsd(ori$xyz[,inds$xyz], res$xyz[,inds$xyz])
```

























































































